version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  commit-message:
    prefix: ci
  groups:
    actions:
      patterns: ['*']
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  commit-message:
    prefix: chore
  groups:
    cargo:
      patterns: ['*']
