repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/redeboer/taplo-pre-commit
  rev: '0.9.1rc1'
  hooks:
  - id: taplo
- repo: local
  hooks:
  - id: cargo-fmt
    name: Rust formatter
    language: rust
    entry: cargo fmt --
    types: [rust]
