repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: ["--fix"]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.1.0
    hooks:
    - id: biome-format
      additional_dependencies: ["@biomejs/biome@1.7.0"]
  - repo: https://github.com/redeboer/taplo-pre-commit
    rev: v0.9.1rc1
    hooks:
      - id: taplo
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: no-commit-to-branch
        args: ["--branch=main"]
