[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.4", features = ["http2", "tokio"] }
axum-github-webhook-extract = "0.2.0"
serde = { version = "1.0.196", features = ["derive"] }
# macros, rt-multi-thread for #[tokio::main]
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.18"
