name: Rust

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build
    - name: Check style
      run: cargo clippy
    - name: Run tests
      run: cargo test
